source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def convenience_pods
    pod "URBNConvenience", :path => "../"
end


target 'Convenience' do
  convenience_pods

  target 'Tests' do
    inherit! :search_paths
  end
end

target 'TVConvenience' do
  convenience_pods

  target 'TVConvenienceTests' do
    inherit! :search_paths
  end
end

