source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Convenience' do
    pod "URBNConvenience", :path => "../"
  target 'Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    # Configure Pod targets for Xcode 8 compatibility
    config.build_settings['SWIFT_VERSION'] = '2.3'
    # Replace XXXXXXXX with your team ID
    # config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'XXXXXXXXXX/'
    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
  end
end
